{{ if and (eq .Cluster.ConfigItems.teapot_admission_controller_service_account_iam "false") (eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true") }}
apiVersion: zalando.org/v1
kind: AWSIAMRole
metadata:
  name: etcd-backup-aws-iam-credentials
  namespace: kube-system
spec:
  roleReference: {{.LocalID}}-etcd-backup
{{ end }}
