kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdp-deployer-poweruser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poweruser
subjects:
- kind: ServiceAccount
  name: cdp
  namespace: default
