apiVersion: v1
kind: Service
metadata:
  labels:
    application: stackset-controller
  name: stackset-controller
  namespace: kube-system
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "7979"
    prometheus.io/scrape: "true"
spec:
  selector:
    application: stackset-controller
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7979
