version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: psa
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
      MYSQL_ROOT_PASSWORD: temppass
  plesk:
    depends_on:
      - db
    build: .
    ports:
      - "8880:8880"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: adminpass
      MYSQL_ROOT_PASSWORD: temppass

volumes:
  db: