{{ if eq .Environment "production" }}
apiVersion: v1
kind: Secret
metadata:
  name: emergency-access-service-secrets
  namespace: kube-system
  labels:
    application: emergency-access-service
type: Opaque
data:
  # value in the following format:
  # {"username": "user", "password": "pass", "magic_token": "token"}
  jira-secrets: "{{ .ConfigItems.emergency_access_service_jira_secrets | base64 }}"
  opentracing-lightstep-access-token: "{{ .ConfigItems.lightstep_token | base64 }}"
{{ end }}
