{{ if and (index .Cluster.ConfigItems "spotio_account_id") (index .Cluster.ConfigItems "spotio_access_token") }}
apiVersion: v1
kind: Secret
metadata:
  name: spotinst-kubernetes-cluster-controller
  namespace: kube-system
  labels:
    application: spotinst-kubernetes-cluster-controller
type: Opaque
data:
  spotinst.token: "{{ .Cluster.ConfigItems.spotio_access_token | base64 }}"
{{ end }}
