apiVersion: v1
kind: Service
metadata:
  labels:
    application: skipper-ingress-redis
  name: skipper-ingress-redis
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    application: skipper-ingress-redis
  type: ClusterIP
